apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifyy-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: artifyy-backend
  template:
    metadata:
      labels:
        app: artifyy-backend
    spec:
      containers:
        - name: backend
          image: 523883707511.dkr.ecr.ap-south-1.amazonaws.com/artifyy-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              value: "mongodb+srv://rishipatel7172:LwqICGoMd3vokXWq@cluster0.odttxqg.mongodb.net/?appName=Cluster0"
            - name: JWT_SECRET
              value: "your_super_secret_key"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"